name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: sudo apt-get install -y autoconf gcc g++ libtool cmake curl
      
    - name: configure
      run: ./configure

    - name: Build
      run: make chrome-build

    - name: Run check
      run: make chrome-checkbuild

